### ISSUE TITLE
race bar charts not loading

### ISSUE THREAD

**Issue by derekeder** [datamade/openness-project-nmid#108]
The bar charts for funds raised aren't rendering on the live site: https://opennessproject.com/

<img width="719" alt="screen shot 2018-01-12 at 11 40 03 pm" src="https://user-images.githubusercontent.com/919583/34903192-ff2c96c4-f7f1-11e7-9d40-73167b7ee6ef.png">

Possibly another issue with static content missing like in #107

**Comment by jeancochrane** [comment]
Static files were owned by the wrong user. Fixed in https://github.com/datamade/openness-project-nmid/commit/27dcd39836e64e5d6acfb556e98eca42cfe516b9.
