### ISSUE TITLE
Monetary amounts should be right aligned

### ISSUE THREAD

**Issue by fgregg** [datamade/openness-project-nmid#110]
![screenshot-2018-1-16 2018 race for lieutenant governor](https://user-images.githubusercontent.com/536941/35000528-43783c4c-faaa-11e7-8ae0-ccedc342c060.png)

From https://nmid.datamade.us/races/1946/

Monetary amounts should right aligned, to make it easier to see differences when they are of different magnitudes.

**Comment by fgregg** [comment]
The monetary amounts for this page are still left justified? https://nmid.datamade.us/races/1624/

**Comment by jeancochrane** [comment]
Whoops, I forgot that was a different template. Good catch!

**Comment by jeancochrane** [comment]
https://github.com/datamade/openness-project-nmid/commit/42dc82ecc3765697ec57df4a19817ccbd8414c3c fixed this issue on staging. Going to hang tight for a production release, since I anticipate more changes will come in today.
