### ISSUE TITLE
It's not clear that the "2018 Race for Governor " on the main page is a link

### ISSUE THREAD

**Issue by fgregg** [datamade/openness-project-nmid#111]
Just saw a user really struggle to figure out that this was a linked even after being told to click on it.

**Comment by jeancochrane** [comment]
I don't actually want users to think of this as the primary link -- it's the header! We already provide buttons to "view more" beneath each table. (I made the headers links on @derekeder's suggestion, in case there are users for whom "header = link" is a presumption.) Closing this for now, although I'm open to hearing arguments against it.
