### ISSUE TITLE
Searchable donor addresses?

### ISSUE THREAD

**Issue by mrchili9** [datamade/openness-project-nmid#121]
How feasible is it to add Donor addresses that are searchable to the page that one arrives at when clicking on a donor's name? It's dawned on me that this would be a really good way for people to see how contribution limits are gotten around, by having multiple people or businesses at the same address donate.

**Comment by jeancochrane** [comment]
Do you mean e.g. this page:

[https://opennessproject.com/search/?term=New%20Mexico%20Federation%20of%20Labor](https://opennessproject.com/search/?term=New%20Mexico%20Federation%20of%20Labor)

![donors](https://user-images.githubusercontent.com/14170650/35536936-0f525d12-050e-11e8-816f-31d4134b4d1a.png)

If it's a matter of adding an extra column and indexing it in the search, that's doable!

**Comment by mrchili9** [comment]
It would be having an address pop up for the Federation of Labor on that
page, and then being able to click on that address to see all other
donations that originated from that address.

What happens is people give under different names and company's that share
the same address. So it would allow you to see how much money is
originating from the same group, or person who's funneling it through other
people or companies.

Marjorie Childress
*Deputy Director*
_______________
New Mexico In Depth
505-410-8487
www.nmindepth.com
Twitter: @NMInDepth
Facebook: facebook.com/NMInDepth/

**Comment by jeancochrane** [comment]
Oh, I see! That'll be a bit more lift in that we'd have to create a whole new page for it. But if we keep it simple (just the address with the list of  PACs that share the address) I think it's doable; we store all that information in a format that makes it relatively accessible, so most of the work will be creating a separate page, adding a column to the search view, and updating the index for the search.

**Comment by jeancochrane** [comment]
A demo of this feature is up on the staging site @mrchili9! [Here's an address search](https://nmid.datamade.us/search/?term=somerville+ma&table_name=candidate&table_name=pac&table_name=contribution&table_name=expenditure):

![somerville-search](https://user-images.githubusercontent.com/14170650/35812279-1c7ef3f4-0a56-11e8-9678-9e0a8db9b1b2.png)

And here's a quick sketch of what [one of those addresses looks like](https://nmid.datamade.us/addresses/260808/) when you select it:

![actblue-address](https://user-images.githubusercontent.com/14170650/35812337-4146fd26-0a56-11e8-8383-187377708acb.png)

From poking around on ActBlue-related addresses, it seems like there are lots and lots of duplicates of addresses: this address in Somerville, for example, is clearly used for many donations (as you can tell from the search) but each instance has its own page. If many addresses are like this, I'm inclined to say we should scrap the separate detail page for the addresses, and just encourage the user to use the search page if they want to see which donations are coming from an address. Browse around some addresses that interest you and let me know what you think about that!

**Comment by mrchili9** [comment]
Hi Jean,

Act Blue is probably like that because it processes so many donations. I
can't think of another organization like that.

But I'm open to scrapping that page, at the moment it's confusing to me
because when I click on addresses I don't see a list of all the donations
from that address. Rather, in some cases it's a cumulative amount without
corresponding dates. I *think* the dates are for the last date a donation
was made. And then there's an issue of addresses not showing up together on
that page because they were spelled slightly different, etc.

If we go with just the ability to search an address, though, it looks like
the actual address doesn't always show up, even when the contributor does.
For instance, searching " PO Box 960 88211 " brings up a page of donations
that when sorted by date shows a descending list of Mack Energy, Broken
Arrow, and Chase Petroleum. But one doesn't see the address next to Broken
Arrow or Chase Petroleum.  Is it possible to ensure the address always
shows up?

Also, is it possible to always have the contributions and expenditures show
up in descending order? Or put a down arrow next to Date so folks know they
can sort? Right now with all the headers in black it's not super intuitive
that they're sortable.

Thanks a bunch!



Marjorie Childress
*Deputy Director*
_______________
New Mexico In Depth
505-410-8487
www.nmindepth.com
Twitter: @NMInDepth
Facebook: facebook.com/NMInDepth/

**Comment by jeancochrane** [comment]
Good call on the sortable columns! I'll add a little icon like we do on the rest of the pages.

I'll take a look at the search term you mentioned as returning empty addresses. If no address shows up in the table, that should mean that we don't have an address on file for that donation -- so I'm confused why it would be returning results that it thinks are relevant.

**Comment by mrchili9** [comment]
The address is definitely connected to those donations, because it shows up
in the data downloads from the SOS site. Our data journalist put together a
table for me with addresses that returned multiple donors. That address, as
an example, had those three companies.

Marjorie Childress
*Deputy Director*
_______________
New Mexico In Depth
505-410-8487
www.nmindepth.com
Twitter: @NMInDepth
Facebook: facebook.com/NMInDepth/

**Comment by jeancochrane** [comment]
I fixed up the missing addresses and added sorting buttons to this page @mrchili9, let me know if it looks good to you: 

https://nmid.datamade.us/search/?term=PO+Box+960+88211&table_name=candidate&table_name=pac&table_name=contribution&table_name=expenditure

**Comment by mrchili9** [comment]
Looks good Jean! Thanks a bunch, excited for how this is coming together.

Marjorie Childress
*Deputy Director*
_______________
New Mexico In Depth
505-410-8487
www.nmindepth.com
Twitter: @NMInDepth
Facebook: facebook.com/NMInDepth/

**Comment by jeancochrane** [comment]
Awesome! Closing this for now, then.
