### ISSUE TITLE
merge candidate functionality

### ISSUE THREAD

**Issue by fgregg** [datamade/openness-project-nmid#203]
we need a feature in the admin interface to merge candidates. here's how i think it should work

1. a search interface to show candidates, probably search by name
2. select one candidate as the survivor and the  one or more others to merge into it the survivor
3. a confirmation dialogue

For each candidate that is getting merged into the filing, for each of their associated filings, committees, and transactions, change their referenced entity id to the survivor's entity id. Once that has changed, then delete the non-surviving merged candidate.

Note: I have already updated the data import scripts so that this should all work out okay. If it's not me that implements this, you should [review the conditions of when a new candidate is created.](https://github.com/datamade/openness-project-nmid/blob/main/camp_fin/management/commands/import_candidates.py#L93-L133).

**Comment by fgregg** [comment]
some prior art:

https://django-extensions.readthedocs.io/en/latest/merge_model_instances.html

https://stackoverflow.com/questions/3393378/django-merging-objects

**Comment by hancush** [comment]
following
