### ISSUE TITLE
Next page not working for individual donors/donations pages

### ISSUE THREAD

**Issue by fgregg** [datamade/openness-project-nmid#35]
On a few pages I've checked, including https://nmid.datamade.us/candidates/hector-balderas-3046/

Doesn't seem to be working for

* largest donations
* largest expenditures
* all donations
* all expenditures

```
Name: Firefox
Version: 48.0
Build ID: 20160728203720
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
OS: Linux 4.4.0-36-generic x86-64
Multiprocess Windows: 0/2 (Disabled by add-ons)
Safe Mode: false
```

**Comment by fgregg** [comment]
And here's why. Clicking that next button makes an *http* request not a *https* request, and my browser is blocking mixed content:

```
Blocked loading mixed active content "http://nmid.datamade.us/api/contributions/?candidate_id=2361&limit=25&offset=25&ordering=-amount"[Learn More]jquery-1.10.1.min.js:6:18214```

**Comment by evz** [comment]
Dammit. It's that thing that Django does when it builds the URLs (we ran into this with councilmatic). Do you remember how we fixed this?

**Comment by evz** [comment]
Added appropriate headers and settings. Updated deployment docs in our ops repo
